version: '0.0.0.{build}'
image: Visual Studio 2017
nuget:
  project_feed: true
  disable_publish_on_pr: true
install:
  - ps: Start-FileDownload "https://raw.githubusercontent.com/vostok/appveyor/master/install.ps1"
configuration: Release
after_build:
  - ps: |
      if ($env:appveyor_repo_branch -eq "master" -and "$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH" -eq "") {
        $proj="Vostok.$env:APPVEYOR_PROJECT_NAME.csproj"
        & $env:cm pack $proj
        if (!$?) {
            Write-Output "cm pack error"
            exit 1
        }
        $csprojs = $env:appveyor_build_folder | Get-ChildItem -Recurse -Filter "*.csproj"
        foreach($csproj in $csprojs)
        {
          $name = $csproj.BaseName
          $nupkgs = Get-ChildItem $env:appveyor_build_folder\$name\bin\Release\$name.*.nupkg
          if ($nupkgs)
          {
            $nupkgs | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
          }          
        }
      }
test_script:
  - ps: |
      if (Test-Path "$env:appveyor_build_folder\Vostok.$env:APPVEYOR_PROJECT_NAME.Tests\Vostok.$env:APPVEYOR_PROJECT_NAME.Tests.csproj")
      {
        dotnet test "$env:appveyor_build_folder\Vostok.$env:APPVEYOR_PROJECT_NAME.Tests\Vostok.$env:APPVEYOR_PROJECT_NAME.Tests.csproj" --logger "trx;LogFileName=tests.trx"
      }
after_test:
  - ps: |
      if (Test-Path "$env:appveyor_build_folder\Vostok.$env:APPVEYOR_PROJECT_NAME.Tests\TestResults\tests.trx") {
      $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:appveyor_job_id)", "$env:appveyor_build_folder\Vostok.$env:APPVEYOR_PROJECT_NAME.Tests\TestResults\tests.trx")
      }
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/f02e74a3a636a56c590b
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
deploy:
  - provider: Environment
    name: Nuget
    on:
      appveyor_repo_tag: true
    artifact: /.*\.nupkg/
  - provider: Environment
    name: FullNuget
    artifact: /.*\.nupkg/
